config/routes.rb
Rails.application.routes.draw do
  get 'profiles/show'


  as :user do
    get 'signup', to: 'devise/registrations#new', as: :signup
    get 'signin', to: 'devise/sessions#new', as: :signin
    get 'signout', to: 'devise/sessions#destroy', as: :logout
  end

  devise_for :users, skip: [:sessions]

  as :user do
    get 'signin', to: 'devise/sessions#new', as: :new_user_session
    post "signin", to: 'devise/sessions#create', as: :user_session
    delete 'signout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :user_friendships do
    member do
      put :accept
      put :block
    end
  end


  resources :statuses
  get 'feed', to: 'statuses#index', as: :feed
  root :to => 'statuses#index'

  get '/:id', to: 'profiles#show', as: 'profile'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = User.find_by_profile_name(params[:id])
    if @user
      @statuses = @user.statuses.order("created_at DESC")
      render action: :show
    else
      render file: 'public/404', status: 404, formats: [:html]
    end
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/show.html.erb
<div class="page-header">
  <h1><%= @user.full_name %></h1>  
</div>
<% if signed_in? %>
  <div id="friend-status">
    <% if current_user.friends.include?(@user) || current_user.pending_friends.include?(@user)%>
      <%= link_to "Edit Friendship", edit_user_friendship_path(friend_id: @user), class: "article-btn" %>
    <% else %>
      <%= link_to "Add Friend", new_user_friendship_path(friend_id: @user), class: "article-btn" %>
    <% end -%>  
  </div>
<% end -%>  
<br>

<% if @statuses %>
  <% @statuses.each do |status| %>
    <div class="well">
      <%= status.content %>
      <hr>
      <%=link_to status.created_at.to_time.strftime('%B %e at %l:%M %p'), status_path(status)%>
    </div>
  <% end -%>
<% end -%>