config/routes.rb
Rails.application.routes.draw do
  get 'profiles/show'


  as :user do
    get 'signup', to: 'devise/registrations#new', as: :signup
    get 'signin', to: 'devise/sessions#new', as: :signin
    get 'signout', to: 'devise/sessions#destroy', as: :logout
  end

  devise_for :users, skip: [:sessions]

  as :user do
    get 'signin', to: 'devise/sessions#new', as: :new_user_session
    post "signin", to: 'devise/sessions#create', as: :user_session
    delete 'signout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :user_friendships do
    member do
      put :accept
      put :block
    end
  end


  resources :statuses
  get 'feed', to: 'statuses#index', as: :feed
  root :to => 'statuses#index'

  get '/:id', to: 'profiles#show', as: 'profile'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user_friendship.rb
class UserFriendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User', foreign_key: 'friend_id'

  after_destroy :delete_mutual_friendship!

  state_machine :state, initial: :pending do
    after_transition on: :accept, do: [:send_acceptance_email, :accept_mutual_friendship!]
    after_transition on: :block, do: [:block_mutual_friendship!]  
    
    state :requested
    state :blocked

    event :accept do
      transition any => :accepted
    end

    event :block do
      transition any => :blocked
    end
  end

  validate :not_blocked

  def self.request(user1, user2)
    transaction do
      friendship1 = create!(user: user1, friend: user2, state: 'pending')
      friendship2 = create!(user: user2, friend: user1, state: 'requested')

      friendship1.send_request_email if !friendship1.new_record?
      friendship1
    end
  end

  def not_blocked
    if UserFriendship.exists?(user_id: user_id, friend_id: friend_id, state: 'blocked') ||
      UserFriendship.exists?(user_id: friend_id, friend_id: user_id, state: 'blocked')
    errors.add(:base, "The friendship cannot be added.")
    end
  end

  def send_request_email
    UserNotifierMailer.friend_requested(id).deliver_now
  end

  def send_acceptance_email
    UserNotifierMailer.friend_request_accepted(id).deliver_now
  end

  def mutual_friendship
    self.class.where({user_id: friend_id, friend_id: user_id}).first    
  end

  def accept_mutual_friendship!
    # Grab the mutual friendship and update the state without using
    # the state machine so as not to invoke callbacks
    mutual_friendship.update_attribute(:state, 'accepted')
  end

  def delete_mutual_friendship!
    mutual_friendship.delete
  end

  def block_mutual_friendship!
    mutual_friendship.update_attribute(:state, 'blocked')if mutual_friendship
  end
end

app/controllers/user_friendships_controller.rb
class UserFriendshipsController < ApplicationController
  before_action :authenticate_user!

  def index
    @user_friendships = friendship_association.all
  end

  def new
    if params[:friend_id]
      @friend =User.where(profile_name: params[:friend_id]).first      
      raise ActiveRecord::RecordNotFound if @friend.nil?
      @user_friendship = current_user.user_friendships.new(friend: @friend)
    else
      flash[:error] = "Friend required"
    end
  rescue ActiveRecord::RecordNotFound
    render file: 'public/404', status: :not_found
  end

  def create
    if params[:user_friendship] && params[:user_friendship].has_key?(:friend_id)
      @friend = User.where(profile_name: params[:user_friendship][:friend_id]).first
      @user_friendship = UserFriendship.request(current_user, @friend)
      if @user_friendship.new_record?
        flash[:error] = "There was a problem creating that friend request."
      else
        flash[:success] = "Friend request sent."
      end
      redirect_to profile_path(@friend)
    else
      flash[:error] = "Friend required"
      redirect_to root_path
    end    
  end

  
  def accept
    @user_friendship = current_user.user_friendships.find(params[:id])
    if @user_friendship.accept!
      flash[:success] = "You are now friends with #{@user_friendship.friend.first_name}"
    else
      flash[:error] = "That friendship could not be accepted."
    end
    redirect_to user_friendships_path
  end

  def block
    @user_friendship = current_user.user_friendships.find(params[:id])
    if @user_friendship.block!
      flash[:success] = "You have blocked #{@user_friendship.friend.first_name}"
    else
      flash[:error] = "That friendship could not be blocked"
    end
    redirect_to user_friendships_path
  end

  def edit
    @friend = User.where(profile_name: params[:id]).first
    @user_friendship = current_user.user_friendships.where(friend_id: @friend.id).first
  end

  def destroy
    @user_friendship = current_user.user_friendships.find(params[:id])
    if @user_friendship.destroy
      flash[:warning] = "Friendship destroyed"
    end
    redirect_to user_friendships_path    
  end

  private

    def friends_params
      # params.require(:user_friendship).permit(:user, :friend, :user_id, :friend_id, :state)
      params.require(:friendship).permit(:user, :friend, :user_id, :friend_id, :state)
    end

    def friendship_association
      case params[:list]
      when nil
        current_user.user_friendships.all
      when 'blocked'
        current_user.blocked_user_friendships.all
      when 'pending'
        current_user.pending_user_friendships.all
      when 'accepted'
        current_user.accepted_user_friendships.all
      when 'requested'
        current_user.requested_user_friendships.all
      end
    end
end

app/helpers/user_friendships_helper.rb
module UserFriendshipsHelper
end

app/views/user_friendships/create.html.erb
create.html.erb

app/views/user_friendships/edit.html.erb
<div class="page-header">
  <h1>Viewing Friendship</h1>
</div>

<div class="row">
  <div class="avatar col-md-2 ">
    <%= image_tag @user_friendship.user.gravatar_url, class:"img" %>
    <%= @user_friendship.user.first_name %>
  </div>
  <div class="avatar col-md-2 ">
    <%= image_tag @user_friendship.friend.gravatar_url, class:"img" %>
    <%= @user_friendship.friend.first_name %>
  </div>

</div>

<% if @user_friendship.requested? %>
  <h3>Do you really want to be friends with <%= @friend.first_name%>?</h3>
<% end -%>

<% if @user_friendship.accepted? %>
  <h3>You are friends with <%= @friend.first_name %></h3>
<% end -%>

<div class="form-actions">
  <% if @user_friendship.requested? %>
    <%= form_for @user_friendship, url: accept_user_friendship_path(@user_friendship), method: :put do |form| %>
      <%= submit_tag "Accept Friendship", class: 'btn btn-primary'%>
    <% end -%>
  <% end -%>
<br>
  <%= form_for @user_friendship, url: block_user_friendship_path(@user_friendship), method: :put do |form| %>
      <%= submit_tag "Block Friendship", class: 'btn btn-default'%>
    <% end -%>
<br>
  <%= form_for @user_friendship, url: user_friendship_path(@user_friendship), method: :delete do |form| %>
      <%= submit_tag "Delete Friendship", class: 'btn btn-danger'%>
  <% end -%>
</div>

app/views/user_friendships/index.html.erb
<div class="page-header">
  <h1>Friends</h1>
</div>

<div>
  <strong>Friend list:</strong>
  <%= link_to 'Blocked', user_friendships_path(list: 'blocked')%>
  <%= link_to 'Requested', user_friendships_path(list: 'requested')%>
  <%= link_to 'Pending', user_friendships_path(list: 'pending')%>
</div>

<% @user_friendships.each do |friendship| %>
  <% friend = friendship.friend %>
  <div id="<%= dom_id(friendship) %>" class="friend row">
    <div class="col-md-1">
      <%= link_to image_tag(friend.gravatar_url), profile_path(friend), class:"img" %>
    </div>
    <div class="col-md-7">
      <strong><%= friend.full_name %></strong><br>
        <% if friendship.pending? %>
          <em>Friendship is pending.</em> <%= link_to "Delete Request", edit_user_friendship_path(friendship.friend.profile_name) %>.
        <% end -%>
        <% if friendship.requested? %>
          <em>Friendship requested.</em> <%= link_to "Accept Friendship", edit_user_friendship_path(friendship.friend.profile_name) %>.
        <% end -%>
        <% if friendship.accepted? %>
          <em>Friendship started <%= friendship.updated_at %>.</em> <%= link_to "Update friendship", edit_user_friendship_path(friendship.friend.profile_name) %>.
        <% end -%>

    </div>
  </div>
<% end -%>

app/views/user_friendships/new.html.erb
<% if @friend %>
  <h1><%= @friend.full_name %></h1>

  <p>Do you really want to friend <%= @friend.full_name %>?</p>
  <%= form_for @user_friendship, method: :post do |form| %>
    <div class="form form-actions">
      <%= form.hidden_field(:friend_id, value: @friend.profile_name) %>
      <%= submit_tag "Yes, Add Friend", class: 'btn btn-success' %>
      <%= link_to "Cancel", profile_path(@friend), class: 'btn btn-default' %>
    </div>
  <% end -%>
<% end -%>