config/routes.rb
Rails.application.routes.draw do
  get 'profiles/show'


  as :user do
    get 'signup', to: 'devise/registrations#new', as: :signup
    get 'signin', to: 'devise/sessions#new', as: :signin
    get 'signout', to: 'devise/sessions#destroy', as: :logout
  end

  devise_for :users, skip: [:sessions]

  as :user do
    get 'signin', to: 'devise/sessions#new', as: :new_user_session
    post "signin", to: 'devise/sessions#create', as: :user_session
    delete 'signout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :user_friendships do
    member do
      put :accept
      put :block
    end
  end


  resources :statuses
  get 'feed', to: 'statuses#index', as: :feed
  root :to => 'statuses#index'

  get '/:id', to: 'profiles#show', as: 'profile'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.order("created_at DESC")
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = current_user.statuses.build
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = current_user.statuses.build(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url, notice: 'Status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:content, :user_id)
    end
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/statuses/_form.html.erb
<%= simple_form_for(status) do |f| %>
  <% if status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(status.errors.count, "error") %> prohibited this status from being saved:</h2>
      <ul>
      <% status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    
    <%= f.input :content, required: false, input_html: { class: 'form-control' } %>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing Status</h1>

<%= render 'form', status: @status %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<div class="page-header">
  <h1>All of the Statuses</h1>
</div>

<%= link_to 'Post a new Status', new_status_path, class: "article-btn" %>

<% @statuses.each do |status| %>
  <% if signed_in? && !current_user.has_blocked?(status.user) || !signed_in? %>
    <div class="status">
      <div class="row">
        <br>
        <div class="col-md-1">
          <%= image_tag status.user.gravatar_url, class:"img" %>
        </div>
        <div class="col-md-7">    
          <strong><%= link_to status.user.full_name, profile_path(status.user) %></strong>
          
          <p><%= status.content.truncate(100) %></p>
          <div class="meta">
            <%= link_to "Created " + (status.created_at.to_time.strftime('%B %e at %l:%M %p')), status %>
            <% if status.user == current_user %>
              <span class="admin">
                | <%= link_to 'Edit', edit_status_path(status) %> |
                <%= link_to 'Destroy', status, method: :delete, data: { confirm: 'Are you sure?' } %>
              </span>
            <% end -%>
          </div>
        </div>
        </br>
      </div>
    </div>
  <% end -%>
<% end %>

app/views/statuses/new.html.erb
<h1>New Status</h1>

<%= render 'form', status: @status %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<br>
<div class="well">
<p>
  <b>Name:</b>
  <%= @status.user.full_name%>
  
</p>

<p>
  <strong>Content:</strong>
  <%= simple_format(@status.content) %>
</p>


<% if @status.user == current_user %>
  <%= link_to 'Edit', edit_status_path(@status) %> |
<% end -%>
<%= link_to 'Back', statuses_path %>
</div>